Gjøre utlån av bok til testbruker når formatklar blir sendt for å trigge distribusjon av ny bok tidligere
nlbdev/produksjonssystem pull request #387
Opened 2023-09-04 15:12 UTC by GauteR

Fixes #386

2023-09-06 12:27 UTC, josteinaj requested changes

2023-09-06 12:27 UTC, josteinaj commented on produksjonssystem/nlbpub_to_epub.py
> +        test_patron_refreshtoken = Config.get("test_patron_refreshtoken")
Refresh token bør ikke hardkodes som miljøvariabel. Bruk heller PIN-koden.

2023-09-06 12:34 UTC, GauteR commented on produksjonssystem/nlbpub_to_epub.py
> +        test_patron_refreshtoken = Config.get("test_patron_refreshtoken")
Mener at det er bedre å bruke Refresh token, siden man da sparer ett kall. På den annen sider ser jeg det er lite hensiktsmessig å måtte bytte ut den hver 180'de dag. Men da blir det mer ett "vedlikeholdsperspektiv" enn ett "sikkerhetsperspektiv".

2023-09-06 13:09 UTC, josteinaj approved these changes
Kjører dette før eller etter formatklar? Usikker på om det har noe å si eller ikke. Ser bra ut :+1:

2023-09-06 15:44 UTC, GauteR commented
Det kjører etter formatklar, hvis jeg leser det riktig

2023-09-07 12:28 UTC, josteinaj approved these changes

2023-09-07 12:29 UTC, merged